### ISSUE TITLE
Domain change to prolific.co

### ISSUE THREAD

**Issue by olliebean** [jurplel/prolific-assistant-fx#3]
Prolific just unexpectedly changed their domain from prolific.ac to prolific.co, and consequently Prolific Assistant FX isn't working now. Could it be updated with the new domain, please?

**Comment by RainyRainer** [comment]
Modified the domain and made a pull request, we just have to wait until Jurplel merges my modifications and publishes an update. For the time being you can email me (me@rainyrainer.com) and I can give you a compiled copy of the updated extension.

**Comment by jurplel** [comment]
Sorry I haven’t been more involved, I’ve been very sick yesterday and today.
